/* --------------------------
    SPLASHTEXTS
    -------------------------- */

splashWordFoods1 = [
    "Pancake",
    "Burger",
    "French Fries",
    "Sandwich",
    "Ice Cream",
]

splashWordFoods2 = [
    "Milkshake",
    "Waffle",
    "Sushi",
    "Apple Pie",
    "Pizza",
]

splashLines = [
    "Hello world!",
    "Welcome to the Fyberverse!",
    "bnuy,,,",
    "ktiy,,,",
    "fxo,,,",
    "meow!",
    "squeak!",
    "This is a splashtext.",
    "IS THAT ARTI???",
    "•- •-• - ••",
    "i like women",
    "You're Loved <3",
    "Your gender is valid!",
    "Show your true colors!",
    "bigender and bisexual call that double gay!",
    "AYAM GORENG!!!",
    "tf is goin on teksui 😭😭🥀🥀",
    ":3",
    "x3",
    "xD",
    ">w<",
    "-w-",
    "/w\\",
    "blehhh",
    "This is fine...",
    "can you guys recommend me splashtexts",
    "Also check out Folder18!",
    "I Wanna Be That Girl!",
    "Stay positive!",
    "TWITTER SUCKS!!! *stays*",
    "We bunnies are superior!",
    "fih 🥀",
    `what kind of universe is "Information" anyway?`,
    "i miss that breakfast girl...",
    "zzz...",
    "How hungry...",
    "If there are two genders, I am both.",
    "Look under there!",
    "Achoo!",
    "Bugs are cool",
    "I'm all ears!",
    "Fiber optic cables not included",
    "This message is considerably rare",
    "Welcoe!",
    "so skibidi",
    "You are beautiful <3",
    "Mom look! I'm a splashtext!",
    "wdym character limit i don",
    "don't bully me i'll cry",
    "🔫🔫🔫 pew pew pew",
    "ERROR 404: Splashtext Not Found",
    "boobies",
    "It's Art 'n' Fyber!",
    "i don't even know anymore",
    "↗️ grown ass woman btw 💀",
    "🌈🍔❤️🏳️‍⚧️🥤",
    "🔥🔥🔥🔥🔥🔥🔥🔥",
    "✋🗿🤚",
    "I'm cringe but I'm free",
    "Trans rights!",
    "why are yall so queer... not complaining",
    `<div style="font-size:16px; transform: rotate(180deg)">upside down!</div>`,
    `<div style="font-size:16px; transform: rotate(180deg)">rotate your monitor</div>`,
    `<div style="font-size:16px; transform: scaleX(-1)">oops! wrong direction...</div>`,
    `<div style="font-size:16px; transform: scaleY(0.8) skew(-80deg)">ow my back hurts</div>`,
    `<a style="font-size:15px; text-decoration: none" href="https://www.youtube.com/watch?v=s-L4DqanZYw" target="_blank" >Click here for a free burger!</a>`,
    `<b style="font-size:16px; color:var(--color-2)">I'M BLUE NOW!</b>`,
    `<b style="font-size:13px; color:var(--color-4)">I'M... red!? wait no this ain't right</b>`,
    `<b style="font-size:15px; color:var(--color-5)">how to reset color???</b>`,
    "undefined",
    "333",
    `<div style="font-size:18px; transform: scaleX(-1)">:3</div>`,
    "Take your age, add 4, that's not your age.",
    "Jkfjhgjhfghkg",
    "🐓   🚓🚓",
    "ARTIFYBER MENTIONED!!",
    "Gay Burger!!",
    "Lesbian Fries!!",
    "Trans Soda!!",
    "Bisexual Pie!!",
    "I swear, these splashtexts are getting ridiculous.",
    `Now with ${totalCards} flavors!`,
    "As seen on Twitter!",
    "Awesome!",
    "Random splashtext!",
    "May contain beans",
    "Made in Fyber's basement!",
    "Also visit Chromasia!",
    "Also visit Klorofil!",
    "Whoa, dude",
    "Stay hydrated!",
    "⁉️",
    "Concentrate the energy in your heart",
    "ERROR 404: Artist Not Found",
    "if (!ok) { return; }",
    "NYA NYA NYA NYA NYA",
    "MRRWW!!",
    "pls rt",
    "FIRE IN THE HOLE!!!",
    "please do something productive",
    "Contains infinite genders!",
    "is this tuff or no",
    `${splashWordFoods1[Math.floor(Math.random() * splashWordFoods1.length)]} is better than ${splashWordFoods2[Math.floor(Math.random() * splashWordFoods2.length)]}`,
    "don't listen to the text below!",
    "don't listen to the next splashtext!",
    "Absolute Cinema",
    "Check out BFDI!",
    "Go follow ZestyLemonss!",
    "Go follow C0denameDelta!",
    "Also listen to Frums!",
    "Also listen to Disphing!",
    "Also listen to YonKaGor!",
    "Also listen to Tanger!",
    "i don't think",
    "you're just gonna click that refresh button again aren't you?",
    "why are you looking at splashtexts anyway?",
    "*paws at you*",
    `Dice be like: IT'S A ${Math.floor(Math.random() * 20) + 1}‼️`,
    "Fyberverse == Artiverse",
    "beep beep i'm a sheep",
    "wrong splashtext srry",
    "Placeholder!",
    "When the fajitas come out sizzling",
    "take your height, swap the feet and inches, that's not your height.",
    "6️⃣7️⃣",
    "Sleeping is the best thing in the world.",
    "LESBIANS EAT WHAT!?",
    "i made mac n cheese :D",
    "RAGEBAIT!",
    "i am at my limit.",
    "24eeev0-$",
    "something terrifying is about to happen...",
    "hello darkness my old friend",
    "i forgor",
    "do you have ibuprofen?",
    "#1 horse hater",
    "Loading...",
    "Black holes are so cool!",
    "colon three",
    "💥💥💥",
    "🐇🐇🐇",
    "Stay safe out there!",
    "Eat more carrots!",
    "Drink more water!",
    "Get some rest!",
    "4:38 AM",
    "testing testing 1 2 3",
    // "hey HEY HEYY WHAT ARE YOU DOING?? you're not supposed to be here!! ewww you're looking at my data... ewwww who are you a perv!?!?!?!?",
    "Down for maintenance. Please come back later.",
    "I CAST BUNNYPILLED!!",
    "I CAST EXCESSIVE FLUFF!!!",
    "Peace! ✌️",
    "we def live in a simulation. and whoever in control is weird af",
    "WE REACHING NANEINF WITH THIS ONE 🔥",
    "caught you reading",
    "made ya look",
    "Mostly salt water!",
    "I squeak, therefore I am.",
    "Did someone say snacks?",
    "Share this website to your friends!",
    "purple buyn",
    "MY FAV FOOD!!!",
    `<div style="font-size:20px; transform: scaleY(0.5)">squishe</div>`,
    "aaaaaaaaaaaaaaaaaaaaaa",
    "is not crash-proof. please be gentle.",
    "This is worth noting!",
    "This is worth nothing!",
    "Starts with A and we all love it!",
    "I like triangles!",
    "I fucking hate javascript",
    `<a style="font-size:18px; text-decoration: none" href="https://www.youtube.com/watch?v=3L7VJl76i9U" target="_blank" >egg</a>`,
    "Now with a rare chance of Beecat!",
    "Good girl/boy/they/it!",
    "hi random guy",
    "🐘",
    "↗️ going to explode in 3 sec",
    "Powered by Omniverse™",
];

totalSplash = splashLines.length;

// splashLines = []
